-- Tạo bảng USERS trước vì các bảng khác sẽ tham chiếu đến nó
CREATE TABLE USERS (
    USER_ID VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    LAST_LOGIN DATETIME,
    FULL_NAME VARCHAR(50),
    DOB DATE,
    PHONE_NUMBER VARCHAR(20),
    GENDER VARCHAR(7),
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tạo bảng USER_SESSIONS, tham chiếu đến USERS
CREATE TABLE USER_SESSIONS (
    SESSION_ID VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    TOKEN VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER_SESSIONS PRIMARY KEY (SESSION_ID),
    CONSTRAINT FK_USER_SESSIONS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tạo bảng EVENTS, thêm cột USER_ID và DESCRIPTION
CREATE TABLE EVENTS (
    EVENT_ID VARCHAR(50) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    POSTER VARCHAR(255),
    POSTER_SUB VARCHAR(255),
    VIDEO VARCHAR(255),
    DESCRIPTION TEXT, -- Thay CLOB bằng TEXT
    START_DATE_TIME DATETIME,
    END_DATE_TIME DATETIME,
    LOCATION VARCHAR(255),
    TICKET_SALE_START DATE,
    TICKET_SALE_END DATE,
    ORGANIZER_NAME VARCHAR(100),
    ORGANIZER_LOGO VARCHAR(255),
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FORMAT VARCHAR(20),
    ORGANIZER_DESCRIPTION TEXT, -- Thay CLOB bằng TEXT
    CONSTRAINT PK_EVENTS PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_EVENTS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tạo bảng TICKET_TYPES, tham chiếu đến EVENTS
CREATE TABLE TICKET_TYPES (
    TICKET_TYPE_ID VARCHAR(50) NOT NULL,
    EVENT_ID VARCHAR(50) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    PRICE DECIMAL(15,2) NOT NULL,
    QUANTITY INT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    MAX_PER_ORDER INT,
    TICKET_SALE_START DATETIME,
    TICKET_SALE_END DATETIME,
    CONSTRAINT PK_TICKET_TYPES PRIMARY KEY (TICKET_TYPE_ID),
    CONSTRAINT FK_TICKET_TYPES_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tạo bảng TICKETS, tham chiếu đến TICKET_TYPES và USERS
CREATE TABLE TICKETS (
    TICKET_ID VARCHAR(50) NOT NULL,
    TICKET_TYPE_ID VARCHAR(50) NOT NULL,
    EVENT_ID VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    PURCHASE_DATE DATETIME,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TICKETS PRIMARY KEY (TICKET_ID),
    CONSTRAINT FK_TICKETS_TICKET_TYPE_ID FOREIGN KEY (TICKET_TYPE_ID) REFERENCES TICKET_TYPES(TICKET_TYPE_ID),
    CONSTRAINT FK_TICKETS_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID),
    CONSTRAINT FK_TICKETS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tạo bảng ORDERS, tham chiếu đến USERS và TICKET_TYPES
CREATE TABLE ORDERS (
    ORDER_ID VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    EVENT_ID VARCHAR(50) NOT NULL,
    TICKET_TYPE_ID VARCHAR(50) NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    TOTAL_AMOUNT DECIMAL(15,2) NOT NULL,
    ORDER_DATE DATETIME NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    PAYMENT_METHOD VARCHAR(50),
    PAYMENT_STATUS VARCHAR(20),
    TRANSACTION_ID VARCHAR(100),
    DISCOUNT DECIMAL(15,2) DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDERS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_ORDERS_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID),
    CONSTRAINT FK_ORDERS_TICKET_TYPE_ID FOREIGN KEY (TICKET_TYPE_ID) REFERENCES TICKET_TYPES(TICKET_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;