server.port=8080
spring.application.name=skycast-gateway

spring.cloud.gateway.routes[0].id=location-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/location/**

spring.cloud.gateway.routes[1].id=weather-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/weather/**
